name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - ipycanvas
  - pip:
      - yjs-widgets>=0.4,<0.5
      - my-jupyter-shared-drive<0.2.0
      - ../python/jupytergis_lab
      - ../python/jupytergis_core
      - ../python/jupytergis_lite
